---

- name: Apache Security | Ensure packages (Debian).
  apt:
    name: ['libapache2-mod-evasive']
    state: present
  notify: restart apache
  tags: [mod_evasive]

- name: Apache Security | Enable Apache mods.
  apache2_module:
    state: present
    name: ['evasive']
  notify: restart apache
  ignore_errors: yes
  tags: [mod_evasive]