---
# tasks file for ansible-role-modevasive


- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [mod_evasive,mod_evasive_cfg]

- name: Default | Check for unsupported target operating system
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported"
  when: supported_os_family|default(False) == False
  tags: [mod_evasive]

# determine apache version
- include: apache-version.yml
  tags: [mod_evasive,mod_evasive_cfg]

- name: Include OS-specific Tasks.
  include: install_Debian.yml
  when: ansible_os_family == 'Debian'
  tags: [mod_evasive]

- name: Include OS-specific Tasks.
  include: install_Redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: [mod_evasive]



- name: Configure mod_evasive
  template:
    src: 'mod_evasive.conf.j2'
    dest: "{{ apache_mods_available }}/{{ me_config_name }}"
    mode: 0644
    owner: root
    group: root
  become: true
  tags: [mod_evasive,mod_evasive_cfg]

  # note we could use a2enconf
- name: Apache | Link in configuration files
  file:
    src: "{{ apache_mods_available }}/{{ item }}"
    dest: "{{ apache_mods_enabled }}/{{ item }}"
    state: link
  with_items:
    - "{{ me_config_name }}"
  when: apache_conf_enable_on
  tags: [mod_evasive,mod_evasive_cfg]
  become: true

- name: ensure log directory exists and is writeable by webserver
  file:
    path: "{{ me_daemon_logdir }}"
    state: directory
    owner: "{{ apache_run_user }}"
    group: "{{ apache_run_group }}"
    mode: 0775
    recurse: no
  become: true
  tags: [mod_evasive, mod_evasive_cfg]

- name: Include IP Tables-specific Tasks.
  include: config_iptables.yml
  when: me_iptables_ban
  tags: [mod_evasive]
